version: '2'
services:
  node1:
    environment:
      - bootstrap.memory_lock=true
    build:
      context: .
      dockerfile: atom.Dockerfile
    ports:
      - "8123:80"
    privileged: true
